language: go
go:
    - 1.7.x

install:
    - mkdir -p $GOPATH/src/github.com/prometheus $GOPATH/src/github.com/opencontainers
    - cd $GOPATH/src/github.com/prometheus && git clone https://github.com/prometheus/client_golang.git && cd client_golang && git checkout v0.8.0
    - cd $GOPATH/src/github.com/opencontainers && git clone https://github.com/opencontainers/runtime-spec && cd runtime-spec && git checkout v1.0.0-rc5
    - cd $GOPATH/src/github.com/containerd/cgroups
    - go get -t ./...

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
